services:
  mysql:
    image: 'mysql:latest'
    container_name: lhvmysql
    environment:
      - 'MYSQL_DATABASE=lhvhomework'
      - 'MYSQL_PASSWORD=secret'
      - 'MYSQL_ROOT_PASSWORD=verysecret'
      - 'MYSQL_USER=lhv'
    ports:
      - '3310:3306'
    networks:
      - lhvhomework
  redis:
    image: 'redis:latest'
    container_name: lhvredis
    ports:
      - '6379'
    networks:
      - lhvhomework
networks:
  lhvhomework:
    driver: bridge